a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
print("Sum :",a+b)
print("Sub:",a-b)
print("mul:",a*b)
print("Div:",a/b)
print("Modulo:",a%b)
print("Exponentiation:",a**b)
print("floor division:",a//b)

